### ISSUE TITLE
Additions to the campaign class for Neuman solution

### ISSUE THREAD

**Issue by JarnoHerr** [GeoStat-Framework/welltestpy#18]
For the implementation of the Neuman solution from Moench et al. 2001 i needed to add:

- Vertical distance above base of aquifer
- Vertical distance from initial water table to bottom of pumped well screen
- Vertical distance from initial water table to top of pumped well screen
- vertical and horizontal hydraulic conductivity 
- specific storage

**Comment by MuellerSeb** [comment]
![scheme](https://user-images.githubusercontent.com/19690642/122229200-d652ff80-ceb8-11eb-820a-6f0a19290b01.png)

This scheme is our reference. For now, I would stick to the observation piezometer.

Most of these values are already present in `welltestpy`:
- `b`: `PumpingTest.aquiferdepth` and `Well.aquiferdepth`
- `l`: `Well.welldepth`
- `z` `Well.aquiferdepth - Well.welldepth`

Missing: `d`: `Well.screendepth`

So the only thing we need to implement in welltestpy is the `screendepth` as an attribute of the `Well` class, that could be none (then we assume a piezometer observation).

The last two parameters mentioned by you are not necessary for welltestpy:
- vertical and horizontal hydraulic conductivity
- specific storage

These are target variables for the estimation and only present in the implementations in AnaFlow.

**Comment by MuellerSeb** [comment]
When adding the new attribute, we need to solve #16, in order to be backward compatible.

**Comment by MuellerSeb** [comment]
We also need to update the documentation of the `Well` attributes in order to clarify, that the well-depth is only the intersection with the saturated zone and the screen-depth is the distance of the screen from to top of the saturated zone.

**Comment by MuellerSeb** [comment]
Instead of using `screendepth`, we could also use `screensize` which defaults to `None` for the current behavior.
The parameter `d` would then be determined by `Well.welldepth - Well.screensize`.
